version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: apix_postgres
    environment:
      POSTGRES_USER: apix
      POSTGRES_PASSWORD: apixpassword
      POSTGRES_DB: apix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apix"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: apix_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: apix_api
    env_file:
      - ./apps/api/.env
    environment:
      DATABASE_URL: postgresql://apix:apixpassword@postgres:5432/apix?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "npm run prisma:deploy && npm run start:prod"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: apix_web
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api/v1
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: sh -c "npm run start"

volumes:
  postgres_data:
  redis_data: