name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
        working-directory: apix-platform
      - name: Build
        run: npm run build
        working-directory: apix-platform
      - name: Type Check
        run: npm run check-types
        working-directory: apix-platform